# -*- coding: utf-8 -*-
"""Graficas en python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pxuMtGWNZ-qdBJT20iJgsbUyHlG2VKgP
"""

import pandas as pd
import matplotlib.pyplot  as plt

aisles1 = pd.read_csv("aisles.csv")
aisles1

departments1 = pd.read_csv("departments.csv")
departments1

order_products__train = pd.read_csv("order_products__train.csv")
order_products__train

orders = pd.read_csv("orders.csv")
orders

products1 = pd.read_csv("products.csv")
products1

sample_submission1 = pd.read_csv("sample_submission.csv")
sample_submission1

pd1 = pd.merge(order_products__train, products1, on = "product_id")
pd1

pd2 = pd.merge(pd1, orders[["order_id", "order_dow", "order_hour_of_day"]], on = "order_id")
pd2

pd3 = pd.merge(pd2, aisles1, on = "aisle_id")
pd3

Dict = {0:'Lunes', 1:'Martes', 2:'Miercoles',3:'Jueves', 4:'Viernes',5:'Sabado', 6:'Domingo'}

pd3['order_dow']=pd3['order_dow'].replace(Dict).astype('string')

pd3

#productos mas vendidos
productos_mas_vendidos = pd3['product_id'].value_counts().nlargest(10)

nombres_productos = pd3[pd3['product_id'].isin(productos_mas_vendidos.index)]['product_name'].unique()

plt.figure(figsize=(10, 5))
plt.bar(nombres_productos, productos_mas_vendidos, color='yellow')
plt.xlabel('Nombre del Producto')
plt.ylabel('Cantidad Vendida')
plt.title('Top 10 Productos Más Vendidos')
plt.xticks(rotation=90)
plt.show()

#Podemos ver que el producto mas vendido es "Bag of organic bananas" con mas de 17500 unidades vendidas
#Esto a partir de cunatas veces aparece el producto "product_id" en "orde_id"

#Prodcutos mas vendidos por por Pasillo y Día de la Semana (Experimento que no salio como esperaba)
pasillo_dia_counts = pd3.groupby(['aisle', 'order_dow'])['product_id'].count().unstack()
ax = pasillo_dia_counts.plot(kind='bar', stacked=True, figsize=(35, 6))

plt.title('Productos Comprados por Pasillo y Día de la Semana')
plt.xlabel('Pasillo')
plt.ylabel('Cantidad de Productos')
plt.legend(title='Día de la Semana', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(rotation=90, ha='right')

plt.show()

#Ventas por dia de la semana
import seaborn as sns

dias = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']

plt.figure(figsize=(10, 6))
sns.countplot(x='order_dow', data = orders, color = "orange")
plt.xlabel('Día')
plt.ylabel('Pedidos')
plt.title('Ventas por día de la semana')
plt.xticks(range(7), dias)
plt.show()

#Como podemos ver en la grafica los dias en que mas productos se compran son los Lunes y Martes
#Estando en numeros similares, en comparacion a los demas dias de la semana
#Asi mismo vemos como el viernes es el dia con menos ventas

#Ventas por hora
import seaborn as sns

plt.figure(figsize=(8,4))
sns.countplot(x = 'order_hour_of_day', data=orders)
plt.xlabel('Hora')
plt.ylabel('Cantidad de Productos Vendidos')
plt.title('Productos Vendidos por Hora')

plt.show()

#Segun la informacion podemos ver que las horas en que mas se venden productos son
#Entre las 10 y 11 am
#Y entre las 2 y 3 pm